/**
 * Generated by Aster
 */
package org.apache.commons.compress.harmony.unpack200.bytecode;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;
import java.util.concurrent.TimeUnit;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class Aster_CPField_Test_Passing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToString_wpxb0() throws Exception {
        CPUTF8 name = new CPUTF8("name");
        CPUTF8 descriptor = new CPUTF8("descriptor");
        CPField cpField = new CPField(name, descriptor, 0, null);
        assertEquals("Field: name(descriptor)", cpField.toString());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToStringWithFlags_jLyE1() throws Exception {
        CPUTF8 name = new CPUTF8("name");
        CPUTF8 descriptor = new CPUTF8("descriptor");
        CPField cpField = new CPField(name, descriptor, 1, null);
        assertEquals("Field: name(descriptor)", cpField.toString());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToStringWithNoParameters_KYjf4() throws Exception {
        CPUTF8 name = new CPUTF8("");
        CPUTF8 descriptor = new CPUTF8("");
        CPField cpField = new CPField(name, descriptor, 0, null);
        assertEquals("Field: ()", cpField.toString());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToStringWithNullName_ApUp5() throws Exception {
        CPUTF8 name = null;
        CPUTF8 descriptor = new CPUTF8("");
        CPField cpField = new CPField(name, descriptor, 0, null);
        assertEquals("Field: (descriptor)", cpField.toString());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToStringWithNullDescriptor_DQKd6() throws Exception {
        CPUTF8 name = new CPUTF8("");
        CPUTF8 descriptor = null;
        CPField cpField = new CPField(name, descriptor, 0, null);
        assertEquals("Field: (null)", cpField.toString());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToStringWithNullNameAndDescriptor_UUsT7() throws Exception {
        CPUTF8 name = null;
        CPUTF8 descriptor = null;
        CPField cpField = new CPField(name, descriptor, 0, null);
        assertEquals("Field: (null)", cpField.toString());
    }
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testToStringWithEmptyName_IflH8() throws Exception {
        CPUTF8 name = new CPUTF8("");
        CPUTF8 descriptor = new CPUTF8("descriptor");
        CPField cpField = new CPField(name, descriptor, 0, null);
        assertEquals("Field: (descriptor)", cpField.toString());
    }
}