# Automatically generated by Pynguin.
import ansible.plugins.inventory.host_list as module_0

def test_case_0():
    inventory_module_0 = module_0.InventoryModule()

def test_case_1():
    str_0 = '-!E@*Mh}I'
    inventory_module_0 = module_0.InventoryModule()
    var_0 = inventory_module_0.verify_file(str_0)
    inventory_module_1 = module_0.InventoryModule()

def test_case_2():
    inventory_module_0 = module_0.InventoryModule()
    str_0 = ''
    var_0 = None
    var_1 = inventory_module_0.parse(inventory_module_0, var_0, str_0)