import unittest
from tornado.queues import *

class TestQueue(unittest.TestCase):
    def test_Queue(self):
        q = Queue()
        self.assertEqual(q.maxsize, 0)
        self.assertEqual(q.qsize(), 0)
        self.assertTrue(q.empty())
        self.assertFalse(q.full())
        self.assertEqual(q.get(), None)
        self.assertEqual(q.get_nowait(), None)
        self.assertEqual(q.put(1), None)
        self.assertEqual(q.put_nowait(1), None)
        self.assertEqual(q.task_done(), None)
        self.assertEqual(q.join(), None)
        self.assertEqual(q.__aiter__(), None)
        self.assertEqual(q._init(), None)
        self.assertEqual(q._get(), None)
        self.assertEqual(q._put(1), None)
        self.assertEqual(q.__put_internal(1), None)
        self.assertEqual(q._consume_expired(), None)
        self.assertEqual(q.__repr__(), None)
        self.assertEqual(q.__str__(), None)
        self.assertEqual(q._format(), None)

    def test_PriorityQueue(self):
        q = PriorityQueue()
        self.assertEqual(q.maxsize, 0)
        self.assertEqual(q.qsize(), 0)
        self.assertTrue(q.empty())
        self.assertFalse(q.full())
        self.assertEqual(q.get(), None)
        self.assertEqual(q.get_nowait(), None)
        self.assertEqual(q.put(1), None)
        self.assertEqual(q.put_nowait(1), None)
        self.assertEqual(q.task_done(), None)
        self.assertEqual(q.join(), None)
        self.assertEqual(q.__aiter__(), None)
        self.assertEqual(q._init(), None)
        self.assertEqual(q._get(), None)
        self.assertEqual(q._put(1), None)
        self.assertEqual(q.__put_internal(1), None)
        self.assertEqual(q._consume_expired(), None)
        self.assertEqual(q.__repr__(), None)
        self.assertEqual(q.__str__(), None)
        self.assertEqual(q._format(), None)

    def test_LifoQueue(self):
        q = LifoQueue()
        self.assertEqual(q.maxsize, 0)
        self.assertEqual(q.qsize(), 0)
        self.assertTrue(q.empty())
        self.assertFalse(q.full())
        self.assertEqual(q.get(), None)
        self.assertEqual(q.get_nowait(), None)
        self.assertEqual(q.put(1), None)
        self.assertEqual(q.put_nowait(1), None)
        self.assertEqual(q.task_done(), None)
        self.assertEqual(q.join(), None)
        self.assertEqual(q.__aiter__(), None)
        self.assertEqual(q._init(), None)
        self.assertEqual(q._get(), None)
        self.assertEqual(q._put(1), None)
        self.assertEqual(q.__put_internal(1), None)
        self.assertEqual(q._consume_expired(), None)
        self.assertEqual(q.__repr__(), None)
        self.assertEqual(q.__str__(), None)
        self.assertEqual(q._format(), None)

if __name__ == '__main__':
    unittest.main()