/**
 * Generated by Aster
 */
package org.apache.commons.jxpath;

import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class Aster_JXPathContextFactoryConfigurationError_Test_Passing {
    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testgetException_NDkP0() {
        JXPathContextFactoryConfigurationError jXPathContextFactoryConfigurationError = new JXPathContextFactoryConfigurationError(new Exception(), "message");
        Exception exception = jXPathContextFactoryConfigurationError.getException();
        assertNotNull(exception);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testgetException2_dBjX1() {
        JXPathContextFactoryConfigurationError jXPathContextFactoryConfigurationError = new JXPathContextFactoryConfigurationError("message");
        Exception exception = jXPathContextFactoryConfigurationError.getException();
        assertNotNull(exception);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testgetException3_LAfJ2() {
        JXPathContextFactoryConfigurationError jXPathContextFactoryConfigurationError = new JXPathContextFactoryConfigurationError();
        Exception exception = jXPathContextFactoryConfigurationError.getException();
        assertNotNull(exception);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testGetMessageWithException_qIFh0() {
        JXPathContextFactoryConfigurationError error = new JXPathContextFactoryConfigurationError(new Exception("test"));
        String message = error.getMessage();
        assertEquals("test", message);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testGetMessageWithMessage_WLtQ1() {
        JXPathContextFactoryConfigurationError error = new JXPathContextFactoryConfigurationError("test");
        String message = error.getMessage();
        assertEquals("test", message);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testGetMessageWithoutParams_kHOb2() {
        JXPathContextFactoryConfigurationError error = new JXPathContextFactoryConfigurationError();
        String message = error.getMessage();
        assertEquals("", message);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testGetMessageWithExceptionAndMessage_fxQn3() {
        JXPathContextFactoryConfigurationError error = new JXPathContextFactoryConfigurationError(new Exception("test"), "test2");
        String message = error.getMessage();
        assertEquals("test2", message);
    }
}