/**
 * Generated by Aster
 */
package com.ibm.websphere.samples.daytrader.web.prims;

import java.util.concurrent.TimeUnit;
import javax.websocket.CloseReason;
import javax.websocket.Session;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
import static org.mockito.Mockito.mock;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class Aster_PingWebSocketTextSync_Test_Passing {
    PingWebSocketTextSync pingwebsockettextsync;
    Session session;
    CloseReason reason;
    private Session currentSession = mock(Session.class);
    private Integer hitCount = 0;

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testOnError_NaaA0() {
        PingWebSocketTextSync sync = new PingWebSocketTextSync();
        Throwable t = new Throwable();
        sync.onError(t);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testOnCloseWithNullSession_XCcg1_UsTK0() {
        PingWebSocketTextSync testee = new PingWebSocketTextSync();
        CloseReason reason = new CloseReason(CloseReason.CloseCodes.NORMAL_CLOSURE, "test");
        testee.onClose(null, reason);
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testOnCloseWithNullSessionAndReason_zbSn3_SVdu0() {
        PingWebSocketTextSync testee = new PingWebSocketTextSync();
        testee.onClose(null, null);
    }
}