/**
 * Generated by Aster
 */
package com.ibm.websphere.samples.daytrader.web.prims.cdi;

import java.util.concurrent.TimeUnit;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class Aster_PingServletCDIBeanManagerViaJNDI_Coverage_Test_Failing {
    PingServletCDIBeanManagerViaJNDI servlet;

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void test_init_0_gjkt0() throws ServletException {
        servlet = new PingServletCDIBeanManagerViaJNDI();
        ServletConfig config = null;
        servlet.init(config);
    }
}