# Automatically generated by Pynguin.
import ansible.modules.command as module_0

def test_case_0():
    pass

def test_case_1():
    bytes_0 = b'ar\x92\x1d0L\x84\x03\x1f\x8e\x11\x0b\xb2(8|\xb0'
    str_0 = '~$D.D '
    var_0 = module_0.check_command(bytes_0, str_0)

def test_case_2():
    var_0 = module_0.main()

def test_case_3():
    str_0 = '__main__'
    complex_0 = None
    str_1 = 'b%<?34lln]E$'
    list_0 = [str_0, str_1, complex_0, str_0]
    var_0 = module_0.check_command(str_1, list_0)