# Automatically generated by Pynguin.
import ansible.utils.collection_loader._collection_finder as module_0

def test_case_0():
    pass

def test_case_1():
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()

def test_case_2():
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()
    str_0 = 'Nw=='
    var_0 = ansible_collection_finder_0.set_playbook_paths(str_0)

def test_case_3():
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()
    str_0 = 'False'
    var_0 = ansible_collection_finder_0.find_module(str_0)

def test_case_4():
    bool_0 = None
    complex_0 = None
    ansible_path_hook_finder_0 = module_0._AnsiblePathHookFinder(bool_0, complex_0)

def test_case_5():
    int_0 = 1022
    str_0 = '^ |'
    ansible_path_hook_finder_0 = module_0._AnsiblePathHookFinder(int_0, str_0)
    var_0 = ansible_path_hook_finder_0.iter_modules(int_0)
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()

def test_case_6():
    str_0 = '~/.ansible/collections/ansible_collections'
    str_1 = '~/.ansible/plugins/modules'
    str_2 = [str_0, str_1]
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder(str_2)

def test_case_7():
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()
    ansible_collection_ref_0 = None
    set_0 = {ansible_collection_finder_0, ansible_collection_finder_0, ansible_collection_finder_0, ansible_collection_ref_0}
    var_0 = ansible_collection_finder_0.set_playbook_paths(set_0)

def test_case_8():
    str_0 = 'F*AVS-jK<7s0'
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder(str_0)
    str_1 = 'ansible_collections.somens.somecoll'
    var_0 = ansible_collection_finder_0.find_module(str_1, str_1)

def test_case_9():
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()
    str_0 = 'H1\nqC7}dToJ'
    float_0 = 3167.8734
    bytes_0 = b'\xd3\xc2\xf141\x1c\xa8'
    ansible_path_hook_finder_0 = module_0._AnsiblePathHookFinder(float_0, bytes_0)
    var_0 = ansible_path_hook_finder_0.find_module(str_0)

def test_case_10():
    str_0 = 'ansible_collections'
    ansible_collection_pkg_loader_base_0 = module_0._AnsibleCollectionPkgLoaderBase(str_0, str_0)

def test_case_11():
    str_0 = 'ansible_collections.foobar.bar'
    str_1 = [str_0]
    ansible_collection_pkg_loader_base_0 = module_0._AnsibleCollectionPkgLoaderBase(str_0, str_1)
    var_0 = ansible_collection_pkg_loader_base_0.get_code(str_0)

def test_case_12():
    str_0 = 'ansible_collections'
    ansible_collection_pkg_loader_base_0 = module_0._AnsibleCollectionPkgLoaderBase(str_0, str_0)
    var_0 = ansible_collection_pkg_loader_base_0.get_source(str_0)

def test_case_13():
    str_0 = 'F*AVS-jK<7s0'
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder(str_0)
    str_1 = 'ansible_collections.somens'
    str_2 = 'ansible_collections.somens.somecoll'
    var_0 = ansible_collection_finder_0.find_module(str_2, str_1)
    str_3 = 'start and step can only be used with integer values'
    var_1 = ansible_collection_finder_0.find_module(str_1, str_3)
    var_2 = ansible_collection_finder_0.find_module(str_2, str_0)

def test_case_14():
    str_0 = 'ansible_collections'
    ansible_collection_finder_0 = module_0._AnsibleCollectionFinder()
    ansible_collection_pkg_loader_base_0 = module_0._AnsibleCollectionPkgLoaderBase(str_0, str_0)
    var_0 = ansible_collection_pkg_loader_base_0.__repr__()

def test_case_15():
    str_0 = 'ansible_collections'
    str_1 = '/some/path'
    str_2 = [str_1]
    ansible_collection_pkg_loader_base_0 = module_0._AnsibleCollectionPkgLoaderBase(str_0, str_2)
    str_3 = 'prefix'
    var_0 = ansible_collection_pkg_loader_base_0.iter_modules(str_3)