/**
 * Generated by Aster
 */
package org.apache.commons.compress.compressors.gzip;
import java.io.IOException;
import java.io.OutputStream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;
import java.util.concurrent.TimeUnit;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
public class Aster_GzipCompressorOutputStream_Test_Passing {
@Test
@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
  void testFlushWithMock_VceF1() throws IOException {
    OutputStream out = mock(OutputStream.class);
    GzipCompressorOutputStream gzipCompressorOutputStream = new GzipCompressorOutputStream(out);
    gzipCompressorOutputStream.flush();
    verify(out, times(1)).flush();
  }
}