/**
 * Generated by Aster
 */
package org.apache.commons.compress.harmony.pack200;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;   
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class Aster_CPMethodOrField_Test_Passing {
private CPMethodOrField cpmethodorfield;
private int indexInClass = -1;
@Mock
    private CPSignature signature;
private int indexInClassForConstructor = -1;
    private CPSignature cpSignature;
}