# Automatically generated by Pynguin.
import ansible.module_utils.facts.system.service_mgr as module_0

def test_case_0():
    pass

def test_case_1():
    service_mgr_fact_collector_0 = module_0.ServiceMgrFactCollector()
    var_0 = service_mgr_fact_collector_0.collect(service_mgr_fact_collector_0)

def test_case_2():
    int_0 = 3095
    str_0 = 'SunOS'
    service_mgr_fact_collector_0 = module_0.ServiceMgrFactCollector(int_0, str_0)
    var_0 = service_mgr_fact_collector_0.collect()
    int_1 = -602
    service_mgr_fact_collector_1 = module_0.ServiceMgrFactCollector(int_1)

def test_case_3():
    str_0 = 'your name <example@domain.com>'
    bool_0 = False
    float_0 = 756.9
    tuple_0 = (str_0, bool_0, float_0)
    dict_0 = {tuple_0: str_0, float_0: tuple_0}
    bytes_0 = b'{\x9b\xe4K+\xcaYZb\xae\xd6\xb6U\xfa'
    str_1 = '\nh")q.n/\\GHc/6lL'
    service_mgr_fact_collector_0 = module_0.ServiceMgrFactCollector(str_1)
    var_0 = service_mgr_fact_collector_0.collect(dict_0, bytes_0)