/**
 * Generated by Aster
 */
package org.apache.commons.jxpath.ri.compiler;

import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class Aster_CoreOperationNegate_Coverage_Test_Passing {
    {
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testgetSymbol_Khta0()
    {
        CoreOperationNegate coreOperationNegate = new CoreOperationNegate(new Constant(""));
        assertEquals("-", coreOperationNegate.getSymbol());
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testIsSymmetric_nVtO0() {
        CoreOperationNegate coreOperationNegate = new CoreOperationNegate(new Constant(""));
        boolean isSymmetric = coreOperationNegate.isSymmetric();
        boolean expected = false;
        assertEquals(expected, isSymmetric);
    }
}