/**
 * Generated by Aster
 */
package org.apache.commons.jxpath.ri.compiler;

import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class Aster_CoreOperationAdd_Coverage_Test_Passing {
    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testIsSymmetric_qwQy0() {
        CoreOperationAdd coreOperationAdd = new CoreOperationAdd(new Expression[0]);
        assertTrue(coreOperationAdd.isSymmetric());
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void getSymbolTest1_WEXc0() {
        CoreOperationAdd coreOperationAdd = new CoreOperationAdd(new Expression[0]);
        String actual = coreOperationAdd.getSymbol();
        String expected = "+";
        assertEquals(expected, actual);
    }

    @Test
    @Timeout(value = 4, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void getPrecedenceTest1_MUBl0_PeUY0() {
        CoreOperationAdd coreOperationAdd = new CoreOperationAdd(new Expression[0]);
        int actual = coreOperationAdd.getPrecedence();
        int expected = 4;
        assertEquals(expected, actual);
    }
}