# Automatically generated by Pynguin.
import ansible.modules.command as module_0

def test_case_0():
    try:
        str_0 = 'warn'
        bool_0 = True
        bool_1 = {str_0: bool_0}
        str_1 = 'ln -s abc def'
        var_0 = module_0.check_command(bool_1, str_1)
    except BaseException:
        pass

def test_case_1():
    try:
        bool_0 = False
        list_0 = [bool_0, bool_0]
        bytes_0 = b'\xd8\x89\x82\xa7\x0f\\\x0c\xacp\x06]\x0c#\xd6Y\xd9\x0ev\x01\xb2'
        var_0 = module_0.check_command(list_0, bytes_0)
        set_0 = {bool_0}
        str_0 = '\nsu'
        var_1 = module_0.check_command(set_0, str_0)
    except BaseException:
        pass