/**
 * Generated by Aster
 */
package org.apache.commons.codec.net;

import java.util.concurrent.TimeUnit;
import org.apache.commons.codec.DecoderException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class Aster_Utils_Test_Passing {
    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testHexDigit_NIuy0_1() {
        assertEquals('0', Utils.hexDigit(0));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testHexDigit_NIuy0_2() {
        assertEquals('F', Utils.hexDigit(15));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testHexDigit_NIuy0_3() {
        assertEquals('4', Utils.hexDigit(20));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testHexDigit_NIuy0_4() {
        assertEquals('F', Utils.hexDigit(-1));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testHexDigit_NIuy0_5() {
        assertEquals('F', Utils.hexDigit(255));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_0_OKkv0() throws DecoderException {
        assertEquals(0, Utils.digit16((byte) '0'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_1_qXjd1() throws DecoderException {
        assertEquals(1, Utils.digit16((byte) '1'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_2_ewzY2() throws DecoderException {
        assertEquals(2, Utils.digit16((byte) '2'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_3_Nola3() throws DecoderException {
        assertEquals(3, Utils.digit16((byte) '3'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_4_TvBV4() throws DecoderException {
        assertEquals(4, Utils.digit16((byte) '4'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_5_XpHA5() throws DecoderException {
        assertEquals(5, Utils.digit16((byte) '5'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_6_lONs6() throws DecoderException {
        assertEquals(6, Utils.digit16((byte) '6'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_7_NuGN7() throws DecoderException {
        assertEquals(7, Utils.digit16((byte) '7'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_8_sFwl8() throws DecoderException {
        assertEquals(8, Utils.digit16((byte) '8'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_9_lRKj9() throws DecoderException {
        assertEquals(9, Utils.digit16((byte) '9'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_A_VFZj10() throws DecoderException {
        assertEquals(10, Utils.digit16((byte) 'A'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_B_AZwX11() throws DecoderException {
        assertEquals(11, Utils.digit16((byte) 'B'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_C_JLid12() throws DecoderException {
        assertEquals(12, Utils.digit16((byte) 'C'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_D_LBxW13() throws DecoderException {
        assertEquals(13, Utils.digit16((byte) 'D'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_E_brtJ14() throws DecoderException {
        assertEquals(14, Utils.digit16((byte) 'E'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testDigit16_F_QuaQ15() throws DecoderException {
        assertEquals(15, Utils.digit16((byte) 'F'));
    }

    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testHexDigit_NIuy0() {
        assertEquals('0', Utils.hexDigit(0));
        assertEquals('F', Utils.hexDigit(15));
        assertEquals('4', Utils.hexDigit(20));
        assertEquals('F', Utils.hexDigit(-1));
        assertEquals('F', Utils.hexDigit(255));
    }
}