/**
 * Generated by Aster
 */
package org.eclipse.cargotracker.infrastructure.messaging.jms;

import jakarta.jms.JMSException;
import jakarta.jms.TextMessage;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class Aster_CargoHandledConsumer_Coverage_Test_Passing {
  @Test
  @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
  public void testOnMessageWithNullTextMessage_emPo2_psXI0() {
    CargoHandledConsumer cargoHandledConsumer = new CargoHandledConsumer();
    TextMessage textMessage = mock(TextMessage.class);
    try {
      when(textMessage.getText()).thenReturn(null);
      cargoHandledConsumer.onMessage(textMessage);
    } catch (JMSException e) {
    }
  }
}